language: java
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
env:
  - SCALA=2.12 JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m"
  - SCALA=nonscala JAVA_OPTS="-Xmx512m" GRADLE_OPTS="-Xms128m"
script:
  - unset _JAVA_OPTIONS
  - env
  - ./gradlew --stacktrace --no-daemon -i check_$SCALA
install: true
